[source]
type = "N2C"
path = "/home/<user>/dolos.socket"

[[reducers]]
type = "AssetHoldersByAsset"
key_prefix = "c2"

[storage]
type = "Mongo"
connection_string = "mongodb://127.0.0.1:27017"
database_name = "scrolls"
collection_name = "data"


[intersect]
type = "Point"
value = [26830198, "6460d563ee97bb106344c972eea10f2b18921ed8ea0516d059005818de3744fb"]

[chain]
type = "Mainnet"

[policy]
missing_data = "Skip"
